#!/bin/bash

cat header.html > picks.html
grep -o -e "\{\"alert\".*pickem\"\}" crap.html > picks.js
grep -o -e "\{\"alert\".*pickem\"\}" crap.html >> picks.html
cat makepicks.js footer.html >> picks.html
