#!/bin/sh
if [ $# != 1 ] ; then
	echo "usage: buy <1-18>"
	exit
fi
if [ ! -e curcard  ] ; then
	./dbd
	echo "===  must draw wildcat card  ==="
	exit
fi
awk -f buy.awk players board curcard plot_in=$1 > msg
./dbd
cat msg
