#!/bin/sh
if [ $# != 3 ] ; then
	echo "usage: makeboard <d1> <d2> <d3>"
	exit
fi
awk -f makeboard.awk plots d1=$1 d2=$2 d3=$3
cp players.init players
cp cards.init cards
rm -f curcard
./dbd
echo "init.1" > curcard
echo "===  each player must now buy a plot  ==="
