var cards = [
    { type: "fire", royalty: 0, ndrills: 0, plotbuy: 0,
      imagesrc: "card_fire.png" },
    { type: "fire", royalty: 0, ndrills: 0, plotbuy: 0,
      imagesrc: "card_fire.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion.png" },
    { type: "production", royalty: 1000, ndrills: 1, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 1, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 3000, ndrills: 1, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 4000, ndrills: 1, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_500_2_none.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_500_2_none.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_500_2_none.png" },
    { type: "production", royalty: 1000, ndrills: 2, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 2, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 3000, ndrills: 2, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 4000, ndrills: 2, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 1000, ndrills: 3, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 3000, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 4000, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 4, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 3000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 4000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
]
