var cards = [
    { type: "fire", royalty: 0, ndrills: 0, plotbuy: 0,
      imagesrc: "card_fire1.png" },
    { type: "fire", royalty: 0, ndrills: 0, plotbuy: 0,
      imagesrc: "card_fire2.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion1.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion2.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion3.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion4.png" },
    { type: "depletion", royalty: 0, ndrills: 1, plotbuy: 0,
      imagesrc: "card_depletion1.png" },
    { type: "production", royalty: 1000, ndrills: 1, plotbuy: 1,
      imagesrc: "card_production_1000_1_one_shopped.png" },
    { type: "production", royalty: 2000, ndrills: 1, plotbuy: 1,
      imagesrc: "card_production_2000_1_one.png" },
    { type: "production", royalty: 3000, ndrills: 1, plotbuy: 0,
      imagesrc: "card_production_3000_1_none_shopped.png" },
    { type: "production", royalty: 4000, ndrills: 1, plotbuy: 0,
      imagesrc: "card_production_4000_1_none.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 1,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_500_2_none1.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_500_2_none2.png" },
    { type: "production", royalty: 500, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_500_2_none3.png" },
    { type: "production", royalty: 1000, ndrills: 2, plotbuy: 1,
      imagesrc: "card_production_1000_2_one.png" },
    { type: "production", royalty: 2000, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_2000_2_none.png" },
    { type: "production", royalty: 3000, ndrills: 2, plotbuy: 0,
      imagesrc: "card_production_3000_2_none.png" },
    { type: "production", royalty: 4000, ndrills: 2, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 3, plotbuy: 1,
      imagesrc: "card_production_500_3_one.png" },
    { type: "production", royalty: 1000, ndrills: 3, plotbuy: 1,
      imagesrc: "card_production_1000_3_one.png" },
    { type: "production", royalty: 2000, ndrills: 3, plotbuy: 0,
      imagesrc: "card_production_2000_3_none.png" },
    { type: "production", royalty: 2000, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 3000, ndrills: 3, plotbuy: 0,
      imagesrc: "card_production_3000_3_none.png" },
    { type: "production", royalty: 4000, ndrills: 3, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 500, ndrills: 4, plotbuy: 1,
      imagesrc: "card_production_500_4_one.png" },
    { type: "production", royalty: 500, ndrills: 4, plotbuy: 0,
      imagesrc: "card_production_500_4_none.png" },
    { type: "production", royalty: 2000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 2000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
    { type: "production", royalty: 3000, ndrills: 4, plotbuy: 0,
      imagesrc: "card_production_3000_4_none.png" },
    { type: "production", royalty: 4000, ndrills: 4, plotbuy: 0,
      imagesrc: "wildcat.png" },
]
