var pipepads = [
    { id: "1-2", plotnumA: 1, plotnumB: 2, owner: -1, pipes: [],
      pipepadleft: 446, pipepadtop: 269, pipeorientation: "vertical" },
    { id: "1-6", plotnumA: 1, plotnumB: 6, owner: -1, pipes: [],
      pipepadleft: 455, pipepadtop: 306, pipeorientation: "horizontal" },
    { id: "1-9", plotnumA: 1, plotnumB: 9, owner: -1, pipes: [],
      pipepadleft: 327, pipepadtop: 443, pipeorientation: "vertical" },
    { id: "1-10", plotnumA: 1, plotnumB: 10, owner: -1, pipes: [],
      pipepadleft: 411, pipepadtop: 439, pipeorientation: "horizontal" },
    { id: "2-3", plotnumA: 2, plotnumB: 3, owner: -1, pipes: [],
      pipepadleft: 547, pipepadtop: 184, pipeorientation: "horizontal" },
    { id: "2-6", plotnumA: 2, plotnumB: 6, owner: -1, pipes: [],
      pipepadleft: 496, pipepadtop: 284, pipeorientation: "vertical" },
    { id: "3-4", plotnumA: 3, plotnumB: 4, owner: -1, pipes: [],
      pipepadleft: 671, pipepadtop: 184, pipeorientation: "horizontal" },
    { id: "3-6", plotnumA: 3, plotnumB: 6, owner: -1, pipes: [],
      pipepadleft: 572, pipepadtop: 258, pipeorientation: "vertical" },
    { id: "3-7", plotnumA: 3, plotnumB: 7, owner: -1, pipes: [],
      pipepadleft: 638, pipepadtop: 260, pipeorientation: "vertical" },
    { id: "4-5", plotnumA: 4, plotnumB: 5, owner: -1, pipes: [],
      pipepadleft: 779, pipepadtop: 270, pipeorientation: "horizontal" },
    { id: "4-7", plotnumA: 4, plotnumB: 7, owner: -1, pipes: [],
      pipepadleft: 709, pipepadtop: 312, pipeorientation: "vertical" },
    { id: "5-7", plotnumA: 5, plotnumB: 7, owner: -1, pipes: [],
      pipepadleft: 744, pipepadtop: 333, pipeorientation: "horizontal" },
    { id: "5-8", plotnumA: 5, plotnumB: 8, owner: -1, pipes: [],
      pipepadleft: 804, pipepadtop: 357, pipeorientation: "vertical" },
    { id: "6-7", plotnumA: 6, plotnumB: 7, owner: -1, pipes: [],
      pipepadleft: 624, pipepadtop: 314, pipeorientation: "horizontal" },
    { id: "6-10", plotnumA: 6, plotnumB: 10, owner: -1, pipes: [],
      pipepadleft: 523, pipepadtop: 385, pipeorientation: "vertical" },
    { id: "7-8", plotnumA: 7, plotnumB: 8, owner: -1, pipes: [],
      pipepadleft: 745, pipepadtop: 424, pipeorientation: "horizontal" },
    { id: "7-11", plotnumA: 7, plotnumB: 11, owner: -1, pipes: [],
      pipepadleft: 723, pipepadtop: 452, pipeorientation: "vertical" },
    { id: "8-11", plotnumA: 8, plotnumB: 11, owner: -1, pipes: [],
      pipepadleft: 802, pipepadtop: 452, pipeorientation: "vertical" },
    { id: "8-12", plotnumA: 8, plotnumB: 12, owner: -1, pipes: [],
      pipepadleft: 931, pipepadtop: 425, pipeorientation: "vertical" },
    { id: "9-10", plotnumA: 9, plotnumB: 10, owner: -1, pipes: [],
      pipepadleft: 394, pipepadtop: 498, pipeorientation: "horizontal" },
    { id: "9-13", plotnumA: 9, plotnumB: 13, owner: -1, pipes: [],
      pipepadleft: 328, pipepadtop: 550, pipeorientation: "vertical" },
    { id: "10-13", plotnumA: 10, plotnumB: 13, owner: -1, pipes: [],
      pipepadleft: 416, pipepadtop: 546, pipeorientation: "vertical" },
    { id: "10-14", plotnumA: 10, plotnumB: 14, owner: -1, pipes: [],
      pipepadleft: 532, pipepadtop: 550, pipeorientation: "vertical" },
    { id: "11-12", plotnumA: 11, plotnumB: 12, owner: -1, pipes: [],
      pipepadleft: 878, pipepadtop: 523, pipeorientation: "horizontal" },
    { id: "11-15", plotnumA: 11, plotnumB: 15, owner: -1, pipes: [],
      pipepadleft: 769, pipepadtop: 552, pipeorientation: "vertical" },
    { id: "12-15", plotnumA: 12, plotnumB: 15, owner: -1, pipes: [],
      pipepadleft: 807, pipepadtop: 607, pipeorientation: "horizontal" },
    { id: "12-18", plotnumA: 12, plotnumB: 18, owner: -1, pipes: [],
      pipepadleft: 875, pipepadtop: 639, pipeorientation: "vertical" },
    { id: "13-14", plotnumA: 13, plotnumB: 14, owner: -1, pipes: [],
      pipepadleft: 439, pipepadtop: 646, pipeorientation: "horizontal" },
    { id: "13-16", plotnumA: 13, plotnumB: 16, owner: -1, pipes: [],
      pipepadleft: 395, pipepadtop: 685, pipeorientation: "vertical" },
    { id: "14-15", plotnumA: 14, plotnumB: 15, owner: -1, pipes: [],
      pipepadleft: 662, pipepadtop: 611, pipeorientation: "horizontal" },
    { id: "14-16", plotnumA: 14, plotnumB: 16, owner: -1, pipes: [],
      pipepadleft: 470, pipepadtop: 675, pipeorientation: "vertical" },
    { id: "14-17", plotnumA: 14, plotnumB: 17, owner: -1, pipes: [],
      pipepadleft: 606, pipepadtop: 675, pipeorientation: "vertical" },
    { id: "15-17", plotnumA: 15, plotnumB: 17, owner: -1, pipes: [],
      pipepadleft: 702, pipepadtop: 671, pipeorientation: "vertical" },
    { id: "15-18", plotnumA: 15, plotnumB: 18, owner: -1, pipes: [],
      pipepadleft: 766, pipepadtop: 678, pipeorientation: "vertical" },
    { id: "16-17", plotnumA: 16, plotnumB: 17, owner: -1, pipes: [],
      pipepadleft: 550, pipepadtop: 780, pipeorientation: "horizontal" },
    { id: "17-18", plotnumA: 17, plotnumB: 18, owner: -1, pipes: [],
      pipepadleft: 724, pipepadtop: 784, pipeorientation: "horizontal" },
]
